<?php
/**
 * $Id$
 * Language labels for database tables/fields belonging to extension "ao_vehicles"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	"default" => Array (
		"tx_aovehicles_vehicles" => "Vehicles",
		"tx_aovehicles_vehicles.model" => "Model",
		"tx_aovehicles_vehicles.image" => "Image",
		"tx_aovehicles_vehicles.type" => "Type",
		"tx_aovehicles_vehicles.brand" => "Brand",
		"tx_aovehicles_vehicles.body" => "Body",
		"tx_aovehicles_vehicles.price" => "Price",
		"tx_aovehicles_vehicles.initial_registration" => "Initial registration",
		"tx_aovehicles_vehicles.mileage" => "Mileage",
		"tx_aovehicles_vehicles.cubic_capacity" => "Cubic capacity",
		"tx_aovehicles_vehicles.power" => "Power",
		"tx_aovehicles_vehicles.gears" => "Gears",
		"tx_aovehicles_vehicles.seats" => "Seats",
		"tx_aovehicles_vehicles.doors" => "Doors",
		"tx_aovehicles_vehicles.gear_shift" => "Gear shift",
		"tx_aovehicles_vehicles.colour" => "Colour",
		"tx_aovehicles_vehicles.metallic" => "Metallic",
		"tx_aovehicles_vehicles.fuel" => "Fuel",
		"tx_aovehicles_vehicles.notes" => "Notes",
		"tx_aovehicles_vehicles.contact" => "Contact",
		"tx_aovehicles_vehicles.equipment" => "Equipment",
		"tx_aovehicles_type" => "Type",
		"tx_aovehicles_type.type" => "Type",
		"tx_aovehicles_brand" => "Brand",
		"tx_aovehicles_brand.brand" => "Brand",
		"tx_aovehicles_body" => "Body",
		"tx_aovehicles_body.body" => "Body",
		"tx_aovehicles_gears" => "Gears",
		"tx_aovehicles_gears.gears" => "Gears",
		"tx_aovehicles_doors" => "Doors",
		"tx_aovehicles_doors.doors" => "Doors",
		"tx_aovehicles_colour" => "Colour",
		"tx_aovehicles_colour.colour" => "Colour",
		"tx_aovehicles_gear_shift" => "Gear shift",
		"tx_aovehicles_gear_shift.gear_shift" => "Gear shift",
		"tx_aovehicles_fuel" => "Fuel",
		"tx_aovehicles_fuel.fuel" => "Fuel",
		"tx_aovehicles_seats" => "Seats",
		"tx_aovehicles_seats.seats" => "Seats",
		"tx_aovehicles_equipment" => "Equipment",
		"tt_content.list_type_pi1" => "AO Vehicles",
	),
	"de" => Array (
		"tx_aovehicles_vehicles" => "Fahrzeuge",
		"tx_aovehicles_vehicles.model" => "Modell",
		"tx_aovehicles_vehicles.image" => "Bild",
		"tx_aovehicles_vehicles.type" => "Fahrzeugart",
		"tx_aovehicles_vehicles.brand" => "Marke",
		"tx_aovehicles_vehicles.body" => "Karosserie",
		"tx_aovehicles_vehicles.price" => "Preis",
		"tx_aovehicles_vehicles.initial_registration" => "Erstzulassung",
		"tx_aovehicles_vehicles.mileage" => "Kilometerstand",
		"tx_aovehicles_vehicles.cubic_capacity" => "Hubraum",
		"tx_aovehicles_vehicles.power" => "Leistung",
		"tx_aovehicles_vehicles.gears" => "Gänge",
		"tx_aovehicles_vehicles.seats" => "Sitzplätze",
		"tx_aovehicles_vehicles.doors" => "Türen",
		"tx_aovehicles_vehicles.gear_shift" => "Getriebeart",
		"tx_aovehicles_vehicles.colour" => "Farbe",
		"tx_aovehicles_vehicles.metallic" => "Metallic",
		"tx_aovehicles_vehicles.fuel" => "Treibstoff",
		"tx_aovehicles_vehicles.notes" => "Bemerkungen",
		"tx_aovehicles_vehicles.contact" => "Ansprechpartner",
		"tx_aovehicles_vehicles.equipment" => "Ausstattung",
		"tx_aovehicles_vehicles.crdate" => "Eingestellt",
		"tx_aovehicles_vehicles.tstamp" => "Aktualisiert",
		"tx_aovehicles_type" => "Fahrzeugart",
		"tx_aovehicles_type.type" => "Fahrzeugart",
		"tx_aovehicles_brand" => "Marke",
		"tx_aovehicles_brand.brand" => "Marke",
		"tx_aovehicles_body" => "Karosserie",
		"tx_aovehicles_body.body" => "Karosserie",
		"tx_aovehicles_gears" => "Gänge",
		"tx_aovehicles_gears.gears" => "Gänge",
		"tx_aovehicles_doors" => "Türen",
		"tx_aovehicles_doors.doors" => "Türen",
		"tx_aovehicles_colour" => "Farbe",
		"tx_aovehicles_colour.colour" => "Farbe",
		"tx_aovehicles_gear_shift" => "Getriebeart",
		"tx_aovehicles_gear_shift.gear_shift" => "Getriebeart",
		"tx_aovehicles_fuel" => "Treibstoffart",
		"tx_aovehicles_fuel.fuel" => "Treibstoffart",
		"tx_aovehicles_seats" => "Sitzplätze",
		"tx_aovehicles_seats.seats" => "Sitzplätze",
		"tx_aovehicles_equipment" => "Ausstattung",
		"tx_aovehicles_equipment.equipment" => "Ausstattung",
		"tt_content.list_type_pi1" => "AO Fahrzeuge",
	),
);
?>